export const endpoint = "http://127.0.0.1:5000"
export const socketEndpoint = "ws://127.0.0.1:5000"
export const uploadOption1 = "Similar file exists here, but my file is an update to it"
export const uploadOption2 = "Exact Law/ regulation file I want to upload again"
export const uploadOption3 = "My law/ regulation file does not exist here"

export const verifyOption1 = "Exact File Already Exist in DB ?"
export const verifyOption2 = "Given File is An Update to existing File"
export const verifyOption3 = "The Given File Does Not Exist IN DB"
export const verifyOption4 = "Invalid File"